name: Build and push CIRCT Windows build docker image

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: circt-windows-build

jobs:
  build-circt-windows-build-image:
    name: Build and push Windows Docker CI builds
    runs-on: windows-2019
    steps:
      - name: Get CIRCT images repo
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      #   with:
      #     images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      #     tags: |
      #       type=sha

      # - name: Build and push Docker image
      #   uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      #   with:
      #     context: "{{defaultContext}}:circt-windows"
      #     push: true
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push windows image
        shell: pwsh
        working-directory: ./circt-windows
        run: |
          $TAG=$(Get-Date -Format yyyyMMddHHmmss)
          docker build . --tag ghcr.io/${{github.repository}}/circt-windows-build:$TAG
          docker push ghcr.io/${{github.repository}}/circt-windows-build:$TAG
          docker tag ghcr.io/${{github.repository}}/circt-windows-build:$TAG ghcr.io/${{github.repository}}/circt-windows-build:latest
          docker push ghcr.io/${{github.repository}}/circt-windows-build:latest
