name: Integration Test Image

on:
  push:
    branches: [trunk]
    paths:
      - 'integration-test/**'
      - '.github/workflows/integration-test.yml'
  pull_request:
    paths:
      - 'integration-test/**'
      - '.github/workflows/integration-test.yml'
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: integration-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build and Push Testing Image
        run: |
          TAG=
          case ${{ github.event_name }} in
            "release")
              TAG=$(echo $GITHUB_REF | cut -d / -f 3)
              ;;
            *)
              TAG="testing"
              ;;
          esac
          docker build . --tag ghcr.io/${{github.repository}}/circt-integration-test:$TAG
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          docker push ghcr.io/${{github.repository}}/circt-integration-test:$TAG
