name: Build and push images

on:
  release: [published]

jobs:
  build-integration-test-image:
    name: Build and push Docker image for integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Get CIRCT images repo
        uses: actions/checkout@v2
      - name: Build image
        working-directory: ./integration_test
        run: |
          TAG=$(echo $GITHUB_REF | cut -d / -f 3)
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          docker build . --tag ghcr.io/${{github.repository}}/circt-integration-test:$TAG
          docker push ghcr.io/${{github.repository}}/circt-integration-test:$TAG
