name: Integration Test Image

on:
  workflow_dispatch:
  push:
    branches: [trunk, main]
    paths:
      - .github/workflows/integration-test.yml
      - install/**
      - integration-test.dockerfile
  pull_request:
    paths:
      - .github/workflows/integration-test.yml
      - install/**
      - integration-test.dockerfile
  release:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup environment
        run: |
          TAG=$(echo $GITHUB_REF | cut -d / -f 3)
          echo "GHCR_TAG=ghcr.io/${{github.repository}}/circt-integration-test:$TAG" >> $GITHUB_ENV

      - name: Build image
        run: docker build . -f integration-test.dockerfile --tag $GHCR_TAG

      - name: Push image
        if: ${{ github.event_name == 'release' }}
        run: |
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          docker push $GHCR_TAG
