name: Build and push PyCDE/ESI test image

on:
  workflow_dispatch:

jobs:
  build-push-image:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - name: Get CIRCT images repo
        uses: actions/checkout@v4
      - name: Build and push image
        run: |
          TAG=$(date -u +%Y%m%d%H%M%S)
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          docker build . -f pycde-esi-test.dockerfile --tag ghcr.io/${{github.repository}}/pycde-esi-test:$TAG
          docker push ghcr.io/${{github.repository}}/pycde-esi-test:$TAG
          docker tag ghcr.io/${{github.repository}}/pycde-esi-test:$TAG ghcr.io/${{github.repository}}/pycde-esi-test:latest
          docker push ghcr.io/${{github.repository}}/pycde-esi-test:latest
