name: Build and push PyCDE build image

on:
  workflow_dispatch:

jobs:
  build-push-image:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - name: Get CIRCT images repo
        uses: actions/checkout@v2
      - name: Build and push image
        working-directory: ./pycde-build
        run: |
          TAG=$(date -u +%Y%m%d%H%M%S)
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          docker build . --tag ghcr.io/${{github.repository}}/pycde-build:$TAG
          docker push ghcr.io/${{github.repository}}/pycde-build:$TAG
          docker tag ghcr.io/${{github.repository}}/pycde-build:$TAG ghcr.io/${{github.repository}}/pycde-build:latest
          docker push ghcr.io/${{github.repository}}/pycde-build:latest
